SELECT * FROM SHARKTANK.DBO.DATASET1;

--TOTAL NO OF EPISODES

SELECT COUNT(DISTINCT EPNO) FROM SHARKTANK..Dataset1;
SELECT MAX(EPNO) FROM SHARKTANK..Dataset1;

--PITCHED FOR THE SHOW

SELECT COUNT (BRAND) FROM SHARKTANK..Dataset1;

--PITCHES CONVERTED INTO A DEAL

SELECT COUNT(DEAL) FROM SHARKTANK..Dataset1 WHERE DEAL  NOT IN ('No Deal','NULL');

SELECT SUM(a.CONVERTED_NOT_CONVERTED) FUNDING_RECEIVED, COUNT(*) TOTAL_PICHES FROM (
SELECT AMOUNTINVESTEDLAKHS, CASE WHEN AMOUNTINVESTEDLAKHS>0	THEN 1 ELSE 0 END AS CONVERTED_NOT_CONVERTED FROM SHARKTANK ..Dataset1)a

--SUCCESS% - PITCHES CONVERTED INTO DEAL

SELECT CAST(SUM(a.CONVERTED_NOT_CONVERTED) AS FLOAT)/CAST(COUNT(*) AS FLOAT) FROM (
SELECT AMOUNTINVESTEDLAKHS, CASE WHEN AMOUNTINVESTEDLAKHS>0	THEN 1 ELSE 0 END AS CONVERTED_NOT_CONVERTED FROM SHARKTANK ..Dataset1)a

--TOTAL MALES

SELECT SUM(MALE) FROM SHARKTANK..Dataset1;

--TOTAL FEMALES

SELECT SUM(FEMALE) FROM SHARKTANK..Dataset1;

--GENDER RATIO

SELECT SUM(FEMALE)/SUM(MALE) FROM SHARKTANK..DATASET1;

--TOTAL INVESTED AMOUNT 

SELECT SUM(AMOUNTINVESTEDLAKHS) FROM SHARKTANK..DATASET1;

--AVERAGE EQUITY TAKEN BY SHARKS 

SELECT AVG(a.EQUITYTAKEN) FROM
(SELECT * FROM SHARKTANK..DATASET1
WHERE EQUITYTAKEN >0)a;

--HIGHEST DEAL TAKEN

SELECT MAX(AMOUNTINVESTEDLAKHS) MAXIMUM_AMOUNT_TAKEN FROM SHARKTANK..DATASET1;

--HIGHEST EQUITY TAKEN

SELECT MAX(EQUITYTAKEN) FROM SHARKTANK..DATASET1;

--STARTUPS HAVING ATLEAST 1 FEMALE 

SELECT SUM(A.FEMALE_COUNT) FROM 
(SELECT FEMALE, CASE WHEN FEMALE>0 THEN 1 ELSE 0 END AS FEMALE_COUNT FROM SHARKTANK..DATASET1)A

--PITCHES CONVERTED HAVING ATLEAST 1 FEMALE

SELECT SUM(FEMALEGOTDEAL) FROM
(SELECT CASE WHEN FEMALE>0 THEN 1 ELSE 0 END AS FEMALEGOTDEAL FROM SHARKTANK..DATASET1
WHERE DEAL != 'NO DEAL')a

--AVERAGE TEAM MEMBER NUMBER

SELECT AVG(TEAMMEMBERS) FROM SHARKTANK..DATASET1;

--AMOUNT INVESTED PER DEAL

SELECT AVG(a.AMOUNTINVESTEDLAKHS) AMOUNT_INVESTED_PERDEAL FROM
(SELECT * FROM SHARKTANK..DATASET1
WHERE DEAL != 'NO DEAL')a

--AVERAGE AGE GROUP OF CONTESTANTS

SELECT AVGAGE,COUNT(AVGAGE)CNT FROM SHARKTANK..DATASET1
GROUP BY AVGAGE
ORDER BY CNT DESC;

--LOCATION FROM WHICH MOST NUMBER OF CONTESTANTS 

SELECT  a.Location,(a.loc_count) FROM
(SELECT LOCATION, COUNT(LOCATION) loc_count FROM SHARKTANK..DATASET1
GROUP BY LOCATION)a
ORDER BY loc_count DESC;

--SECTOR FROM WHICH MOST NUMBER OF CONTESTANTS

SELECT  a.SECTOR,a.SECTOR_count FROM
(SELECT SECTOR, COUNT(SECTOR) SECTOR_count FROM SHARKTANK..DATASET1
GROUP BY SECTOR)a
ORDER BY SECTOR_count DESC

--PARTNER DEALS BETWEEN ALL THE SHARKS

SELECT PARTNERS,COUNT(PARTNERS) COUNT_PARTNERS FROM SHARKTANK..DATASET1
WHERE PARTNERS != '-'
GROUP BY PARTNERS
ORDER BY COUNT_PARTNERS DESC;


---MAKE THE MATRIX WHICH INCLUDE ALL THE SHARKS AND SHOWS INDIVIDUALLY
--1. TOTAL DEALS IN WHICH SHARK PRESENT
--2. TOTAL DEALS IN WHICH SHARK INVESTED
--3. TOTAL AMOUNT INVESTED BY THE SHARK AND
--4. AVERAGE EQUITY TAKEN BY THE SHARK

--ASHNEER--
--NUMBER OF DEALS IN WHICH ASHNEER WAS PRESENT

SELECT COUNT(ASHNEERAMOUNTINVESTED) FROM SHARKTANK..DATASET1 WHERE ASHNEERAMOUNTINVESTED IS NOT NULL;

--NUMBER OF DEALS IN WHICH ASHNEER HAD INVESTED

SELECT COUNT(ASHNEERAMOUNTINVESTED) FROM SHARKTANK..DATASET1 WHERE ASHNEERAMOUNTINVESTED IS NOT NULL and ASHNEERAMOUNTINVESTED!=0

--TOTAL AMOUNT INVESTED AND AVERAGE EQUITY TAKEN BY ASHNEER

SELECT SUM(C.ASHNEERAMOUNTINVESTED), AVG(C.ASHNEEREQUITYTAKEN) 
FROM (SELECT * FROM SHARKTANK..DATASET1 WHERE ASHNEEREQUITYTAKEN !=0 AND ASHNEEREQUITYTAKEN IS NOT NULL)C

--MAKING ROW FOR ASHNEER

SELECT m.keyy, m.TOTAL_DEALS_PRESENT,m.TOTAL_DEALS,n.keyy,n.TOTALAMOUNTINVESTED,n.TOTALEQUITYTAKEN FROM

(SELECT a.keyy,a.TOTAL_DEALS_PRESENT,b.TOTAL_DEALS FROM
(
SELECT 'ASHNEER' AS KEYY, COUNT(ASHNEERAMOUNTINVESTED) TOTAL_DEALS_PRESENT FROM SHARKTANK..DATASET1 WHERE ASHNEERAMOUNTINVESTED IS NOT NULL)a

INNER JOIN

(SELECT 'ASHNEER' AS KEYY, COUNT(ASHNEERAMOUNTINVESTED) TOTAL_DEALS FROM SHARKTANK..DATASET1 WHERE ASHNEERAMOUNTINVESTED IS NOT NULL 
and ASHNEERAMOUNTINVESTED!=0) b

ON a.keyy = b.keyy) m

INNER JOIN

(SELECT 'ASHNEER' AS KEYY, SUM(C.ASHNEERAMOUNTINVESTED) TOTALAMOUNTINVESTED, AVG(C.ASHNEEREQUITYTAKEN)TOTALEQUITYTAKEN
FROM (SELECT * FROM SHARKTANK..DATASET1 WHERE ASHNEEREQUITYTAKEN !=0 AND ASHNEEREQUITYTAKEN IS NOT NULL)C)n

ON m.keyy = n.keyy


--STARTUP IN WHICH THE HIGHEST AMOUNT HAS BEEN INVESTED IN EACH SECTOR

SELECT a.brand,a.SECTOR, a.AmountInvestedlakhs,A.rnk FROM
(SELECT BRAND,SECTOR,AmountInvestedlakhs,rank() over (partition by SECTOR order by AmountInvestedlakhs desc)rnk FROM SHARKTANK..DATASET1
) a
WHERE rnk IN (1)
